name: rybo_kalkulator
description: Aplikacja do wyceny ryb MVP.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Ikony
  cupertino_icons: ^1.0.2
  # Baza danych
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Stan
  provider: ^6.0.5
  # Aparat/Galeria
  image_picker: ^1.0.4
  # Pliki
  path_provider: ^2.1.1
  # Daty i waluty
  intl: ^0.18.1
  # ID
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Generatory kodu (niezbÄ™dne do Hive)
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true